# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.FloatField()),
                ('name', models.CharField(max_length=48)),
                ('ref', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=16)),
                ('oneway', models.IntegerField()),
                ('bridge', models.IntegerField()),
                ('maxspeed', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=21037)),
            ],
        ),
    ]
