# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 17:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0002_roads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Railways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.FloatField()),
                ('name', models.CharField(max_length=48)),
                ('type', models.CharField(max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=21037)),
            ],
        ),
    ]
