# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0007_auto_20160711_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cameras',
        ),
    ]
