# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0009_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.FloatField()),
                ('timestamp', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=48)),
                ('type', models.CharField(max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
