# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0010_construct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=80)),
                ('ward', models.CharField(max_length=80)),
                ('constituen', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
