# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapgis', '0015_auto_20160711_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidents',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 7, 11, 16, 54, 59, 495579, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
    ]
